# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBI-Printf
version:      0.03
version_from: lib/DBI/Printf.pm
installdirs:  site
requires:
    DBI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
